### ISSUE TITLE
does the plugin supports kodi 14.2?

### ISSUE THREAD

**Issue by holywen** [zhengfan2014/xbmc-kodi-private-china-addons#1]
Thanks for your efforts to create those great plugins!
And How to install the needed addons like:  xbmcswift2

**Comment by holywen** [comment]
For bilibili plugin, the dependencies are:
    <import addon="script.module.xbmcswift2" version="2.4.0"/>
  <import addon="script.module.beautifulsoup4" version="4.5.3"/>
  <import addon="script.module.requests" version="2.19.1"/>
  <import addon="script.module.html5lib" version="0.999.0"/>

and what I found is only script.module.request does not satisfied, helix provided 2.15.1 (https://mirrors.kodi.tv/addons/helix/script.module.requests/) and here we need 2.19.1,for the other modules,

**Comment by zhengfan2014** [comment]
我没有kodi14.2的开发环境，目前暂时没有办法尝试支持kodi14.2。不过你可以尝试修改插件依赖所需要的版本号为你的kodi所支持的版本号，也许可以正常运行，祝好运

I didn't kodi14.2 Currently, there is no way to try to support kodi14.2 。 However, you can try to change the version number required by the plug-in dependency to the version number supported by your Kodi. It may work normally. Good luck

**Comment by holywen** [comment]
Thanks, I tried but it doesn't work.
