### ISSUE TITLE
请问bilibili插件是否有显示弹幕功能？

### ISSUE THREAD

**Issue by shaolin-kongfu** [zhengfan2014/xbmc-kodi-private-china-addons#2]
如题

**Comment by zhengfan2014** [comment]
目前暂无弹幕功能，因为kodi目前不支持xml字幕（弹幕），不过中文插件库的bilibili有弹幕功能，是通过xml转ass字幕实现的，还是有实现的可能的。

**Comment by shaolin-kongfu** [comment]
我也觉得可以调用其他开发者的项目链接去下载xml再转成ass，大佬有打算开发吗？

**Comment by zhengfan2014** [comment]
> 我也觉得可以调用其他开发者的项目链接去下载xml再转成ass，大佬有打算开发吗？

有这个打算，不过以我目前的三脚猫编程短时间内可能写不出来😂

**Comment by shaolin-kongfu** [comment]
不知道ack-Cherish的爬虫项目对你是否有帮助，里面也涉及了下载xml以及转换为ass的部分
https://github.com/Jack-Cherish/python-spider/blob/master/bilibili/bilibili.py
我刚学python，看到你的代码2000+行，头有点晕

**Comment by zhengfan2014** [comment]
> 我编写了下载xml以及转换为ass的部分（需要aid）
> https://github.com/shaolin-kongfu/danmu
> 大佬把它缝合到你的项目里试试？？
> 我刚学python，看到你的代码2000+行，头有点晕

wow，谢谢，不过缝合到我的项目可能还需要一些时间。我的想法是写成独立的字幕插件，这样就可以在视频播放途中随时打开/关闭弹幕，不过字幕插件我从来没写过，网上的适合萌新的参考资料也少，所以短时间内可能做不出来😂

看代码晕挺正常的，说实话现在我看taxigps大佬的字幕插件代码也晕，我建议先从简单的入手，比如那个停更的澎湃插件，用个vscode，边运行，边调试。你可以尝试把所有代码删光，保留import 那些还有入口文件，然后看kodi.log报错，差什么补什么，理解一下整个澎湃插件的运行流程。然后再研究更复杂的

附几个可能有帮助的文档：
xbmcswift2文档：https://xbmcswift2.readthedocs.io/en/latest/
kodi的python文档：https://codedocs.xyz/xbmc/xbmc/group__python.html

**Comment by shaolin-kongfu** [comment]
好的谢谢，字母插件的想法好像有点不对劲，现有的字幕插件不都是在字幕网站直接获取的吗？感觉直接把弹幕在你的项目里下载然后放到缓冲视频的同级目录，这样不是也可以让用户选择打开或关闭吗
