### ISSUE TITLE
bangumi插件多个网站失效

### ISSUE THREAD

**Issue by karma-sun** [zhengfan2014/xbmc-kodi-private-china-addons#27]
**描述错误**
bangumi插件里面以下网站，源网站全部失效了
guguani.me,qinmei.video,ningmoe.com,tucao.one,clicli.me,zzzfun.com

**Comment by zhengfan2014** [comment]
其他几个意料之中，zzzfun估计原来反爬的换了吧，吐槽失效倒是有些意外😂待修bug+1

**Comment by karma-sun** [comment]
貌似项目已废弃
