### ISSUE TITLE
项目Github Workflow的默认branch写错了。

### ISSUE THREAD

**Issue by ArchieMeng** [zhengfan2014/xbmc-kodi-private-china-addons#28]
现在这个项目有py2和py3两条分支，而zip workflow里写的是master分支，然后我看到的就是最近几次PR检查都失败了。

**Comment by zhengfan2014** [comment]
没改是因为准备用python重写下workflow，shell不如python好用😂

**Comment by ArchieMeng** [comment]
原来是这样啊。那没事了。。。
