### ISSUE TITLE
AcFun插件在观看视频时提示404

### ISSUE THREAD

**Issue by Sokwva** [zhengfan2014/xbmc-kodi-private-china-addons#5]
AcFun插件在观看普通视频视频（如娱乐区或者音乐区等区块的视频）时提示：
“错误404，世界线变动....”
信息。

观察了一下，www.acfun.cn/rest/pc-direct/rank/channel 此接口返回的信息的videoList中已不会返回videoSource信息；可能需要寻找新的接口。

**Comment by zhengfan2014** [comment]
能提供一下具体的ac号吗，我这里测试音乐区几个视频可以正常打开
![U2sxk4.png](https://s1.ax1x.com/2020/07/18/U2sxk4.png)

**Comment by Sokwva** [comment]
我使用的是电视上面的kodi arm64 ，kodi 18 leia；刚刚测试查看的视频是综合模块的 https://www.acfun.cn/v/ac16840932

**Comment by zhengfan2014** [comment]
> 我使用的是电视上面的kodi arm64 ，kodi 18 leia；刚刚测试查看的视频是综合模块的 https://www.acfun.cn/v/ac16840932

我用电脑和安卓手机的kodi复现不出你说的错误。不过看描述我猜可能是242~263的代码执行出现了valueerror错误，具体哪一行我不也太确定。😂

如果你的电脑运行kodi也可以复现错误的话，可以参考这里
[如何边运行边调试kodi插件？](https://github.com/zhengfan2014/xbmc-kodi-private-china-addons/wiki/%E5%A6%82%E4%BD%95%E8%BE%B9%E8%BF%90%E8%A1%8C%E8%BE%B9%E8%B0%83%E8%AF%95kodi%E6%8F%92%E4%BB%B6%EF%BC%9F)
[kodi日志文件具体位置和定位错误](https://github.com/zhengfan2014/xbmc-kodi-private-china-addons/wiki/kodi%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6%E5%85%B7%E4%BD%93%E4%BD%8D%E7%BD%AE%E5%92%8C%E5%AE%9A%E4%BD%8D%E9%94%99%E8%AF%AF)

尝试复制try:里所有内容（图中选中的）
![Uh07oF.png](https://s1.ax1x.com/2020/07/20/Uh07oF.png)
到except ValueError:里
![UhBWkD.png](https://s1.ax1x.com/2020/07/20/UhBWkD.png)
然后再次执行acfun插件，插件报错后整个日志文件上传到github或者把错误行截图。我看看能不能修😂

如果电脑无法复现的话&不是很懂python也可以直接下载我下面修改好的acfun插件，运行后报错，用es文件管理器把日志文件拷贝到u盘再通过电脑上传
[plugin.video.acfun.zip](https://github.com/zhengfan2014/xbmc-kodi-private-china-addons/files/4945861/plugin.video.acfun.zip)

kodi.log直接拖到github回复里就可以上传
![UhspwV.png](https://s1.ax1x.com/2020/07/20/UhspwV.png)
[![UhsMFO.png](https://s1.ax1x.com/2020/07/20/UhsMFO.png)](https://imgchr.com/i/UhsMFO)
