### ISSUE TITLE
请教如何播放弹幕

### ISSUE THREAD

**Issue by lsl330** [zhengfan2014/xbmc-kodi-private-china-addons#8]
举例我的本地nas里存放了一些动画，并在并将同名的xml弹幕文件一同存放在动画文件夹里
请问有办法在点击播放视频播放视频的时候直接加载xml弹幕文件播放弹幕么？（哪怕自动将xml转换成ass播放也可以）
可以的话，麻烦告知具体实现方法，万分感谢

**Comment by zhengfan2014** [comment]
如果你是指在windows上的话，poplayer和一些像弹弹play貌似可以直接加载xml的弹幕。

如果是kodi的话，暂时没有办法。因为kodi不认xml弹幕，据我所知只能手动转码的方式，或者通过b站字幕插件来下载并转换为ass（就像我nas的jellyfin mp4可以转码，mkv不能转码。只能电脑手动mkv转mp4，再上传回nas才能在jellyfin上看一样蛋疼）

不过，自动将xml转ass的话倒是有这种可能。就是需要自己造轮子😂

> 举例我的本地nas里存放了一些动画，并在并将同名的xml弹幕文件一同存放在动画文件夹里
> 请问有办法在点击播放视频播放视频的时候直接加载xml弹幕文件播放弹幕么？（哪怕自动将xml转换成ass播放也可以）
> 可以的话，麻烦告知具体实现方法，万分感谢

**Comment by lsl330** [comment]
是的，我现在就是在androidtv上播放弹幕没有找到很好的解决办法。
弹弹play有安卓版，但在androidtv上对遥控器的支持有不少的问题，操作会很麻烦。但的确个人感觉是目前看弹幕最实用的办法了。
plex、emby、jellyfin这些都不支持播放弹幕。
kodi倘若可以直接转xml成ass，然后加载的话也算是折中方案，但看来是不太可行了。
> 如果你是指在windows上的话，poplayer和一些像弹弹play貌似可以直接加载xml的弹幕。
> 
> 如果是kodi的话，暂时没有办法。因为kodi不认xml弹幕，据我所知只能手动转码的方式，或者通过b站字幕插件来下载并转换为ass（就像我nas的jellyfin mp4可以转码，mkv不能转码。只能电脑手动mkv转mp4，再上传回nas才能在jellyfin上看一样蛋疼）
> 
> 不过，自动将xml转ass的话倒是有这种可能。就是需要自己造轮子😂
