### ISSUE TITLE
场库插件和taptap插件播放视频报错

### ISSUE THREAD

**Issue by karma-sun** [zhengfan2014/xbmc-kodi-private-china-addons#9]
只能显示视频列表，播放就报错

**Comment by zhengfan2014** [comment]
感谢反馈，taptap目前在修了，场库和新片场有修复的计划

**Comment by karma-sun** [comment]
貌似项目已不维护

**Comment by ArchieMeng** [comment]
新片场有个PR: https://github.com/zhengfan2014/xbmc-kodi-private-china-addons/pull/33 你看看能不能用？
另外，我有空也不是不能看一看这个问题。

**Comment by karma-sun** [comment]
> 新片场有个PR: #33 你看看能不能用？ 另外，我有空也不是不能看一看这个问题。

这个项目还是用的python2,已经不能用在现在的kodi上了，需要有人重开新项目基于python3做

**Comment by ArchieMeng** [comment]
> 这个项目还是用的python2,已经不能用在现在的kodi上了，需要有人重开新项目基于python3做

有py3分支可以用于现在的kodi上，而且上面那个PR就是python3的。
